typography_spectrum: 0.4325168523937464
color:
  brandColors:
    - '#1b1930'
    - '#384055'
    - '#ffffff'
    - '#222339'
    - '#2f3449'
  brandStrength: 0
  lightness: 0.2575522968545556
  saturation: 0.4955740408040583
  rhythmicContrast: 0.012113874545320868
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5771725096274167
analytics:
  google: null
  facebook: null
  twitter: null
name: DOMINICAN PERFUMES
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'Test '
    id: 4799b3a4-233e-4365-b7c3-6d707c2e561e
    type: content
favicon: null
title: MAGDALENA MARIA
description: 'The Essence of being beautiful '
purpose: []
